ConsenSys/doc.common

- custom_theme/assets/stylesheets/custom.css
- add arrow symbol on all links that makes user leave the doc site
f360 character is https://fontawesome.com/icons/external-link-square-alt
- update copyright size to prevent it to be on be on multiple lines due to new links icons
fixes PegaSysEng/Misc#17
> add external link symbol

- .github/ISSUE_TEMPLATE/bug_report.md
replace 3 dots `...` by the unique symbol`…`
> fix ellipsis symbol

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
> Added nodejs

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
> Adding words for Tessera

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: Byron Gravenorst <byron.gravenorst@consensys.net>
> Add Pyrmont to accepted word list.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: Byron Gravenorst <byron.gravenorst@consensys.net>
> Add subnets to accepted word list.

- build_tools/linkchecker/link_check_conf.json
Exclude github orchestrate private repo
> Exclude github orchestrate private repo

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
> Add rollups.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
> Add words for Sumo.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
change accepted text from "Metamask" to "MetaMask".
> Metamask -> MetaMask

- build_tools/linkchecker/link_check_conf.json
Signed-off-by: Byron Gravenorst <byron.gravenorst@consesnsys.net>
> Add Zendesk link.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: Byron Gravenorst <byron.gravenorst@consesnsys.net>
> Add network names.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: Byron Gravenorst <byron.gravenorst@consesnsys.net>
> add websockets.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Reverts ConsenSys/doc.common#37
> Revert "add websockets."

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Signed-off-by: Byron Gravenorst <byron.gravenorst@consesnsys.net>
> Add websockets and arity.

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Add "Jubjub" to `accept.txt` (for Baby Jubjub elliptic curve in Quorum Key Manager).
> add "Jubjub"

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Add `Etherscan`, `kubectl`, `Helmfile`, `minikube`, and `Rinkeby` to accept.
> Add five words to accept.txt

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
add "Doctools" to `accept.txt`
> add Doctools

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Add `Kaleido` (the blockchain service provider) to `accept.txt`.
> add "Kaleido"

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Add "Prysm" and "pre" to accept.txt (for Merge docs)
> add "Prysm" and "pre"

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
> add failover

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
> add "Sepolia" to vocab

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
Add "doppelganger" to accept.txt.
> add "doppelganger"

- build_tools/vale/vale_styles/Vocab/Consensys/accept.txt
> add "liveness"
